version: "3.7"

services:
  app:
    image: mysql:8.0.29
    container_name: mysql-test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test_pw
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci