spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: test_pw
logging:
  level:
    org.springframework.r2dbc.core: debug